### ISSUE TITLE
デスクトップの解像度取得について

### ISSUE THREAD

**Issue by babcs2035** [K-Bwamske/Performance_Mgr#1]
Menu.cppの51~53行目の処理において、
起動した際、ウィンドウのタスクバーが画面外に出てしまう現象がおきた。
恐らく、タスクバーを除いたウィンドウの左上をデスクトップの左上に合わせてしまっている
からだと思うんだけど、改善方法はないかな？

![2016-12-15 13 14 45](https://cloud.githubusercontent.com/assets/22171273/21211631/8b89982a-c2c8-11e6-847b-f62857241091.png)

（Issuesのテストも兼ねて）

**Comment by Kuske** [comment]
前回のウィンドウの位置にウィンドウを合わせたらどうでしょうか
確かそんなことができる関数があったはず

**Comment by Kuske** [comment]
Bwambocosさん
WindowSizeMgr.cppの27行目でファイルポインタにfprintf()してますよ

**Comment by babcs2035** [comment]
だ、だめだっけ？

**Comment by Kuske** [comment]
すいません
間違えました
sprintf()と勘違いしてた

**Comment by Bwambocos** [comment]
探してみるよー

**Comment by babcs2035** [comment]
解決した

**Comment by Kuske** [comment]
何が原因だったの？
