### ISSUE TITLE
起動時の挙動

### ISSUE THREAD

**Issue by Kuske** [K-Bwamske/Performance_Mgr#14]
起動したときの挙動が変です（前の動画でわかると思う）
原因は DxLib_Init() の前に設定するところを後から設定しているからだと思う
それを直したいんですがやってもいいでしょうか

**Comment by babcs2035** [comment]
よき。
fix_bugかなんかで作業して下さいませ。

**Comment by Kuske** [comment]
Bwambocosさんも手伝ってくれると信じてます

**Comment by babcs2035** [comment]
実は某『ごすてーじ』をやってたり。
あと今22:22

**Comment by babcs2035** [comment]
今のMenu_Init()でウィンドウ関係とか全部やってるの違和感が出てきた気がします。
自分で速攻で書いちゃったんだけどね...

**Comment by Kuske** [comment]
ですよね

**Comment by Kuske** [comment]
終わったので閉じますね
